branches:
  only:
    - 'master'

env:
  - RAILS_ENV=test DB=mysql
  - RAILS_ENV=test DB=sqlite

language: ruby

rvm:
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 2.0.0

bundler_args: "--without development"

before_script:
  - "cp config/database.$DB.yml config/database.yml"
  - "cp config/initializers/config.example.rb config/initializers/config.rb"
  - "bundle exec rake db:create db:migrate subwire:setup db:test:prepare"

script:
  - "bundle exec rspec"
