source 'http://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'mysql2'
gem 'coffee-rails', '~> 3.2.1'
gem 'uglifier', '>= 1.0.3'
gem 'sass-rails',   '~> 3.2.3'
gem 'twitter-bootstrap-rails'
gem 'jquery-rails'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'devise'
gem 'ckeditor'
gem 'will_paginate'
gem 'will_paginate_twitter_bootstrap'
gem 'paperclip'
